services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - streamflix_mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: streamflix

volumes:
  streamflix_mongo_data:
